apiVersion: v1
kind: Service
metadata: 
  name: frontend-svc
  namespace: webapps
spec:
  ports:
  - port: 80
    targetPort: 3000  # Target the container's port
    protocol: TCP
  type: LoadBalancer
  selector:
    app: frontend
    version: blue  # This can be change to "green" when switching traffic
