apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname  # Name of the secret
  namespace: webapps  # Namespace where the secret will be created
  annotations:
    kubernetes.io/service-account.name: jenkins  # Links to the service account

#NB: after creating secret run the following commands
# kubectl get secret mysecretname -o jsonpath='{.data.token}' | base64
# kubectl get secret
# kubectl describe secret mysecretname
# Copy token